--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/08/2023 04:09:20 p. m.
-- Server version: 5.5.5-10.4.24-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE sartech_gtninmuebles;

--
-- Drop table `administradores`
--
DROP TABLE IF EXISTS administradores;

--
-- Drop table `anuncios`
--
DROP TABLE IF EXISTS anuncios;

--
-- Drop table `articulos`
--
DROP TABLE IF EXISTS articulos;

--
-- Drop table `banner`
--
DROP TABLE IF EXISTS banner;

--
-- Drop table `cartas`
--
DROP TABLE IF EXISTS cartas;

--
-- Drop table `categorias`
--
DROP TABLE IF EXISTS categorias;

--
-- Drop table `clientes`
--
DROP TABLE IF EXISTS clientes;

--
-- Drop table `inmuebles`
--
DROP TABLE IF EXISTS inmuebles;

--
-- Drop table `landing_page`
--
DROP TABLE IF EXISTS landing_page;

--
-- Drop table `leads`
--
DROP TABLE IF EXISTS leads;

--
-- Drop table `menu`
--
DROP TABLE IF EXISTS menu;

--
-- Drop table `nosotros`
--
DROP TABLE IF EXISTS nosotros;

--
-- Drop table `opiniones`
--
DROP TABLE IF EXISTS opiniones;

--
-- Drop table `personal`
--
DROP TABLE IF EXISTS personal;

--
-- Drop table `servicios`
--
DROP TABLE IF EXISTS servicios;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Set default database
--
USE sartech_gtninmuebles;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  id int(11) NOT NULL AUTO_INCREMENT,
  login varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `servicios`
--
CREATE TABLE servicios (
  id_servicio int(11) NOT NULL AUTO_INCREMENT,
  titulo_tarjeta varchar(255) DEFAULT NULL,
  nombre_servicio varchar(255) DEFAULT NULL,
  img_servicio varchar(255) DEFAULT NULL,
  ruta_servicio varchar(255) DEFAULT NULL,
  descripcion_corta_servicio varchar(255) DEFAULT NULL,
  descripcion_servicio varchar(255) DEFAULT NULL,
  palabras_claves varchar(255) DEFAULT NULL,
  caracteristicas varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_servicio)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `personal`
--
CREATE TABLE personal (
  id_personal int(11) NOT NULL AUTO_INCREMENT,
  id_usuario int(11) DEFAULT NULL,
  PRIMARY KEY (id_personal)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `opiniones`
--
CREATE TABLE opiniones (
  id_opinion int(11) NOT NULL AUTO_INCREMENT,
  id_art int(11) NOT NULL,
  nombre_opinion text NOT NULL,
  correo_opinion text NOT NULL,
  foto_opinion text NOT NULL,
  contenido_opinion text NOT NULL,
  id_adm int(11) DEFAULT NULL,
  respuesta_opinion text DEFAULT NULL,
  aprobacion_opinion int(11) DEFAULT NULL,
  fecha_opinion date NOT NULL,
  fecha_respuesta timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP () ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id_opinion)
)
ENGINE = INNODB,
AUTO_INCREMENT = 22,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `nosotros`
--
CREATE TABLE nosotros (
  id_nosotros int(11) NOT NULL AUTO_INCREMENT,
  valores_corto varchar(255) DEFAULT NULL,
  valores_completo longtext DEFAULT NULL,
  img_valores varchar(255) DEFAULT NULL,
  mision_corto varchar(255) DEFAULT NULL,
  mision_completo longtext DEFAULT NULL,
  img_mision varchar(255) DEFAULT NULL,
  vision_corto varchar(255) DEFAULT NULL,
  vision_completo longtext DEFAULT NULL,
  img_vision varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_nosotros)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `menu`
--
CREATE TABLE menu (
  id int(11) NOT NULL AUTO_INCREMENT,
  etiqueta varchar(255) DEFAULT NULL,
  ruta_menu varchar(255) DEFAULT NULL,
  activo int(11) DEFAULT NULL,
  fecha_menu timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP () ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 10922,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `leads`
--
CREATE TABLE leads (
  id_lead varchar(255) NOT NULL,
  PRIMARY KEY (id_lead)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `landing_page`
--
CREATE TABLE landing_page (
  id int(11) NOT NULL,
  dominio varchar(255) NOT NULL,
  titulo varchar(255) NOT NULL,
  descripcion varchar(255) NOT NULL,
  palabras_claves varchar(255) NOT NULL,
  portada varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  logo varchar(255) NOT NULL,
  icono varchar(255) NOT NULL,
  redes_sociales varchar(255) NOT NULL,
  sobre_mi varchar(255) NOT NULL,
  sobre_mi_completo varchar(255) NOT NULL,
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP () ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `inmuebles`
--
CREATE TABLE inmuebles (
  id_inmueble int(11) NOT NULL AUTO_INCREMENT,
  titulo varchar(255) DEFAULT NULL,
  descripcion varchar(255) DEFAULT NULL,
  direccion varchar(255) DEFAULT NULL,
  recamaras varchar(255) DEFAULT NULL,
  baños varchar(255) DEFAULT NULL,
  medios_baños varchar(255) DEFAULT NULL,
  autos varchar(255) DEFAULT NULL,
  metros_construccion varchar(255) DEFAULT NULL,
  metros_terreno varchar(255) DEFAULT NULL,
  palabras_clave varchar(255) DEFAULT NULL,
  img_principal varchar(255) DEFAULT NULL,
  fecha timestamp NULL DEFAULT NULL,
  estado varchar(255) DEFAULT NULL,
  municipio varchar(255) DEFAULT NULL,
  colonia varchar(255) DEFAULT NULL,
  codigo_postal varchar(255) DEFAULT NULL,
  calle varchar(255) DEFAULT NULL,
  numero_interior varchar(255) DEFAULT NULL,
  numero_exterior varchar(255) DEFAULT NULL,
  Tipo_inmueble varchar(255) DEFAULT NULL,
  ruta_inmueble varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_inmueble)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  id_cliente int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id_cliente)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `categorias`
--
CREATE TABLE categorias (
  id_categorias int(11) NOT NULL AUTO_INCREMENT,
  titulo_categoria varchar(255) DEFAULT NULL,
  descripcion_categoria varchar(255) DEFAULT NULL,
  palabras_claves_categoria varchar(255) DEFAULT NULL,
  ruta_categoria varchar(255) DEFAULT NULL,
  img_categoria varchar(255) DEFAULT NULL,
  fecha timestamp NULL DEFAULT NULL,
  activo int(11) DEFAULT NULL,
  pagina varchar(255) DEFAULT NULL,
  subcategoriade varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_categorias)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `cartas`
--
CREATE TABLE cartas (
  id_card int(11) NOT NULL AUTO_INCREMENT,
  titulo_card varbinary(255) DEFAULT NULL,
  descripcion_card varchar(255) DEFAULT NULL,
  img_card varchar(255) DEFAULT NULL,
  ruta_card varchar(255) DEFAULT NULL,
  palabras_claves_card varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_card)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `banner`
--
CREATE TABLE banner (
  id_banner int(11) NOT NULL AUTO_INCREMENT,
  pagina_banner text NOT NULL,
  titulo_banner text DEFAULT NULL,
  descripcion_banner text DEFAULT NULL,
  img_banner text NOT NULL,
  fecha_banner timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP () ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id_banner)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `articulos`
--
CREATE TABLE articulos (
  id_articulo int(11) NOT NULL AUTO_INCREMENT,
  id_cat int(11) DEFAULT NULL,
  portada_articulo varchar(255) DEFAULT NULL,
  titulo_articulo varchar(255) DEFAULT NULL,
  descripcion_articulo varchar(255) DEFAULT NULL,
  ruta_articulo varchar(255) DEFAULT NULL,
  palabras_claves_art varchar(255) DEFAULT NULL,
  contenido_articulo longtext DEFAULT NULL,
  vistas_articulo int(11) DEFAULT NULL,
  fecha_articulo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP () ON UPDATE CURRENT_TIMESTAMP,
  prologo varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_articulo)
)
ENGINE = INNODB,
AUTO_INCREMENT = 52,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `anuncios`
--
CREATE TABLE anuncios (
  id_anuncio int(11) NOT NULL AUTO_INCREMENT,
  pagina_anuncio text NOT NULL,
  codigo_anuncio text NOT NULL,
  fecha_anuncio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP (),
  PRIMARY KEY (id_anuncio)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `administradores`
--
CREATE TABLE administradores (
  id_admin int(11) NOT NULL AUTO_INCREMENT,
  nombre_admin text NOT NULL,
  correo_admin text NOT NULL,
  foto_admin text NOT NULL,
  fecha_admin timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP (),
  PRIMARY KEY (id_admin)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table usuarios
--
-- Table sartech_gtninmuebles.usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table servicios
--
INSERT INTO servicios VALUES
(1, 'Inicial', 'Inicial', NULL, 'incial', 'Pagina Web Inicial', 'Pagina para dar a conocer tu marca al mundo', '', NULL);

-- 
-- Dumping data for table personal
--
-- Table sartech_gtninmuebles.personal does not contain any data (it is empty)

-- 
-- Dumping data for table opiniones
--
-- Table sartech_gtninmuebles.opiniones does not contain any data (it is empty)

-- 
-- Dumping data for table nosotros
--
-- Table sartech_gtninmuebles.nosotros does not contain any data (it is empty)

-- 
-- Dumping data for table menu
--
INSERT INTO menu VALUES
(5, 'INICIO', 'inicio', 1, '2022-11-25 14:55:14'),
(6, 'NOSOTROS', 'nosotros', 1, '2023-08-21 15:43:13'),
(7, 'BLOG', 'blog', 1, '2023-08-08 11:54:01');

-- 
-- Dumping data for table leads
--
-- Table sartech_gtninmuebles.leads does not contain any data (it is empty)

-- 
-- Dumping data for table landing_page
--
INSERT INTO landing_page VALUES
(0, 'http://localhost/gtninmuebles/', 'GTNInmuelbes', 'soluciones en informatica', '["paginas web","sitios web", "diseño web"]', '', '', 'vistas/img/logo.png', '', '[\r\n{"red":"facebook","url":"https://www.facebook.com", "icono":"fab fa-facebook-f", "background":"#1475E0"},\r\n{"red":"instagram","url":"https://www.instagram.com", "icono":"fab fa-instagram", "background":"#B18768"}\r\n]', '', '', '2023-08-22 11:42:56');

-- 
-- Dumping data for table inmuebles
--
INSERT INTO inmuebles VALUES
(1, 'Casa en Venta', 'Propiedad de 410 m2, casa con cuatro habitaciones, cochera para tres autos, dos baños completos, patio de servio, cocina, sala y comedor, terrasa', 'San Isidro ejidal', '4', '2', '0', '4', '220', '410', NULL, '/vistas/img/inmuebles/san_isidro.jpg', '2023-08-22 00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Departamento', 'Departamento en cuarto piso, dos habitaciones, estudio, baño , sala - comedor, patio de servicio', 'Los Arcos, Zapopan', '2', '1', '0', '2', '61', NULL, NULL, '/vistas/img/inmuebles/local.jpeg', '2023-08-22 00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3, 'Local en Renta', 'Local plata alta en renta ', 'Av. tesistan', '2', '1', '0', '0', '61', '61', NULL, '/vistas/img/inmuebles/los_arcos_2.jpg', '2023-08-22 00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table clientes
--
-- Table sartech_gtninmuebles.clientes does not contain any data (it is empty)

-- 
-- Dumping data for table categorias
--
INSERT INTO categorias VALUES
(1, 'Venta', NULL, NULL, 'Venta', NULL, NULL, 1, 'blog', NULL),
(2, 'Renta', NULL, NULL, 'Renta', NULL, NULL, 1, 'blog', NULL),
(3, 'Asesor Inmobiliario', NULL, NULL, 'Asesor-Inmobiliario', NULL, NULL, 1, 'blog', NULL),
(4, 'Inicio', NULL, NULL, 'inicio', NULL, NULL, 1, 'inicio', NULL),
(5, 'blog', NULL, NULL, 'blog', NULL, NULL, 1, 'inicio', NULL);

-- 
-- Dumping data for table cartas
--
INSERT INTO cartas VALUES
(1, x'56656E746120646520496E6D7565626C6573', 'Vendemos tu propiedad y te acompañamos en todo todo el proceso de compraventa', NULL, 'Venta-de-Inmuebles', NULL),
(2, x'52656E7461', 'Que rentar tu propiead no sea un dolor de cabeza', NULL, 'Renta', NULL),
(3, x'416E616C69736973206465206D65726361646F20636F6D706172617469766F', 'Conoce cuanto vale tu propiedad en el mercado', NULL, 'Analisis-de-mercado-comparativo', NULL);

-- 
-- Dumping data for table banner
--
-- Table sartech_gtninmuebles.banner does not contain any data (it is empty)

-- 
-- Dumping data for table articulos
--
INSERT INTO articulos VALUES
(31, 1, 'vistas/img/logo.png', 'Preparación es la Clave', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Preparacion-es-la-Clave', NULL, 'Antes de poner tu propiedad en el mercado, es crucial que te asegures de que esté en las mejores condiciones posibles. Esto incluye realizar cualquier reparación necesaria, pintar las paredes si es necesario y llevar a cabo una limpieza profunda. Un espacio limpio y bien cuidado dará una primera impresión positiva a los potenciales compradores.', 1, '2023-08-22 14:02:56', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(32, 1, 'vistas/img/logo.png', 'Asesoramiento Profesional', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Asesoramiento-Profesional', NULL, 'Contar con la asesoría de un agente inmobiliario profesional puede marcar la diferencia en el proceso de venta. Los agentes inmobiliarios tienen experiencia en la evaluación de propiedades, la fijación de precios adecuados y la creación de estrategias de marketing efectivas. Además, pueden manejar las negociaciones y los trámites legales, ahorrándote tiempo y preocupaciones.', 1, '2023-08-22 14:04:09', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(33, 1, 'vistas/img/logo.png', 'Presentación Fotográfica Atractiva', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', ' Presentacion-Fotografica-Atractiva', NULL, 'En el mundo digital actual, las imágenes de alta calidad son esenciales para atraer a posibles compradores. Asegúrate de que las fotos de tu propiedad muestren sus mejores aspectos. La buena iluminación y el enfoque en los puntos fuertes de la propiedad pueden hacer una gran diferencia en la impresión que los compradores potenciales tendrán.', NULL, '2023-08-22 14:04:10', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(34, 1, 'vistas/img/logo.png', 'Estrategia de Marketing Personalizada', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Estrategia-de-Marketing-Personalizada', NULL, 'Cada propiedad es única, por lo que la estrategia de marketing también debe serlo. Tu agente inmobiliario puede ayudarte a desarrollar un plan de marketing que incluya listados en línea, publicidad en redes sociales, folletos impresos y más. Llegar a una audiencia amplia y relevante aumentará las posibilidades de encontrar al comprador adecuado.', NULL, '2023-08-22 14:04:11', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(35, 1, 'vistas/img/logo.png', 'Flexibilidad en las Visitas', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Flexibilidad-en-las-Visitas', NULL, 'Estar dispuesto a programar visitas a la propiedad en horarios convenientes para los compradores potenciales puede ser clave. La flexibilidad para mostrar la propiedad puede aumentar tus posibilidades de recibir ofertas.', NULL, '2023-08-22 14:04:11', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(36, 1, 'vistas/img/logo.png', 'Precio Realista', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Precio-Realista', NULL, 'Precio-Realista', NULL, '2023-08-22 14:04:11', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(37, 1, 'vistas/img/logo.png', 'Negociación Habilidosa', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Negociacion-Habilidosa', NULL, 'Las negociaciones son una parte fundamental de la venta de propiedades. Prepárate para negociar con los compradores potenciales, manteniendo en mente tus objetivos y límites. Tu agente inmobiliario puede ayudarte a gestionar estas negociaciones de manera profesional.', 1, '2023-08-22 14:04:12', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(38, 1, 'vistas/img/logo.png', 'Preparación Legal', 'Consejos Esenciales para una Exitosa Venta de Propiedades: Guía de la Inmobiliaria GTNInmuebles', 'Preparacion-Legal', NULL, 'A medida que se acerca el cierre de la venta, asegúrate de estar al tanto de los requisitos legales y documentación necesaria. Contar con un abogado especializado en transacciones inmobiliarias puede garantizar que todos los aspectos legales se aborden correctamente.', 1, '2023-08-22 14:04:12', 'La venta de propiedades puede ser un proceso emocionante y desafiante, pero con la orientación adecuada y una estrategia sólida, puede lograrse con éxito. Al seguir estos consejos esenciales de nuestra inmobiliaria, estará mejor preparado para vender su p'),
(39, 2, 'vistas/img/logo.png', 'Investigación de Mercado y Fijación de Precios', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Investigacion-de-Mercado-y-Fijación-de-Precios', NULL, 'Antes de anunciar su propiedad en alquiler, es fundamental realizar una investigación exhaustiva del mercado. Analice propiedades similares en su área para obtener una idea de los precios de alquiler actuales. Fijar un precio competitivo y realista es esencial para atraer a posibles inquilinos.', NULL, '2023-08-22 14:04:12', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(40, 2, 'vistas/img/logo.png', 'Preparacion del Inmueble', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Preparacion-de-Inmueble', NULL, 'Al igual que con la venta de propiedades, la presentación es clave. Asegúrese de que su inmueble esté en excelentes condiciones antes de mostrarlo a los posibles inquilinos. Realice reparaciones necesarias, aplique una capa de pintura fresca si es necesario y mantenga una limpieza impecable.', NULL, '2023-08-22 14:04:13', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(41, 2, 'vistas/img/logo.png', 'Creación de un Anuncio Atractivo', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Creacion-deo- un-Anuncio-Atractivo', NULL, 'La presentación en línea es crucial en el proceso de renta. Cree un anuncio detallado y atractivo que resalte las características únicas de su propiedad. Utilice fotografías de alta calidad y describa las comodidades y beneficios que ofrece el inmueble y su ubicación.', NULL, '2023-08-22 14:04:13', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(42, 2, 'vistas/img/logo.png', 'Proceso de Selección de Inquilinos', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Proceso-de-Seleccion-de-Inquilinos', NULL, 'La selección de inquilinos es un paso crítico para garantizar una experiencia de alquiler exitosa. Realice una evaluación cuidadosa de los posibles inquilinos, incluida la revisión de antecedentes y referencias. Esto ayudará a asegurarse de que los inquilinos sean confiables y cumplan con sus obligaciones.', NULL, '2023-08-22 14:04:13', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(43, 2, 'vistas/img/logo.png', 'Elaboración de un Contrato de Arrendamiento Sólido', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Elaboracion-de-un-Contrato-de-Arrendamiento-Solido', NULL, 'Un contrato de arrendamiento bien redactado es esencial para proteger sus intereses como arrendador. Asegúrese de que el contrato incluya todos los términos y condiciones importantes, como la duración del arrendamiento, el monto del alquiler y las responsabilidades de ambas partes.', NULL, '2023-08-22 14:04:14', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(44, 2, 'vistas/img/logo.png', 'Mantenimiento Regular', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Mantenimiento-Regular', NULL, 'A lo largo del arrendamiento, es crucial mantener una comunicación abierta con los inquilinos y brindar un mantenimiento regular de la propiedad. Responda rápidamente a las solicitudes de reparación y asegúrese de que el inmueble se mantenga en buenas condiciones.', NULL, '2023-08-22 14:04:14', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(45, 2, 'vistas/img/logo.png', 'Gestionar las Finanzas de Manera Eficiente', 'Guía Completa para la Renta de Inmuebles: Consejos de GTNInmuebles', 'Gestionar-las-Finanzas-de-Manera-Eficiente', NULL, 'Llevar un registro preciso de los pagos de alquiler y los gastos relacionados con la propiedad es esencial. Utilice herramientas de contabilidad o software de gestión de propiedades para mantener un registro organizado de las transacciones financieras.', 1, '2023-08-22 14:04:14', 'La renta de inmuebles puede ser una inversión rentable y gratificante, siempre y cuando se aborde con una planificación y enfoque adecuados. Siguiendo los consejos proporcionados por nuestra inmobiliaria, estará mejor preparado para enfrentar los desafíos'),
(46, 3, 'vistas/img/logo.png', 'Expertise y Conocimiento del Mercado', 'El Rol Crucial del Asesor Inmobiliario', 'El-Rol-Crucial-del-Asesor-Inmobiliario', NULL, 'Los asesores inmobiliarios son profesionales altamente capacitados y con un profundo conocimiento del mercado inmobiliario. Están al tanto de las tendencias actuales, los precios de mercado y las condiciones que pueden afectar las transacciones inmobiliarias. Este conocimiento les permite brindar asesoramiento informado para ayudarte a tomar decisiones inteligentes.', 1, '2023-08-22 14:36:32', 'En el emocionante y complejo mundo de bienes raíces, contar con el asesoramiento de un experto es esencial para garantizar una experiencia exitosa y sin complicaciones. Los asesores inmobiliarios no solo aportan conocimiento y experiencia, sino que tambié'),
(47, 3, 'vistas/img/logo.png', 'Evaluación y Análisis Detallado', 'El Rol Crucial del Asesor Inmobiliario', 'Evaluacion-y-Analisis-Detallado', NULL, 'Cuando se trata de comprar o vender una propiedad, la evaluación precisa es crucial. Los asesores inmobiliarios pueden analizar minuciosamente las propiedades, considerando factores como ubicación, tamaño, estado de la propiedad y comparables en el mercado. Esta evaluación es esencial para establecer precios justos y para asegurarse de que una propiedad se ajuste a tus objetivos y necesidades.', 1, '2023-08-22 14:36:38', 'En el emocionante y complejo mundo de bienes raíces, contar con el asesoramiento de un experto es esencial para garantizar una experiencia exitosa y sin complicaciones. Los asesores inmobiliarios no solo aportan conocimiento y experiencia, sino que tambié'),
(48, 3, 'vistas/img/logo.png', 'Asesoramiento Personalizado', 'El Rol Crucial del Asesor Inmobiliario', 'Asesoramiento-Personalizado', NULL, 'Cada situación inmobiliaria es única, y es aquí donde el asesor inmobiliario brilla al ofrecer asesoramiento personalizado. Escucharán tus metas, deseos y preocupaciones, y trabajarán contigo para desarrollar una estrategia que se adapte a tus necesidades específicas. Ya sea que estés buscando tu primer hogar, una inversión o vender una propiedad, el asesor te guiará en cada paso.', NULL, '2023-08-22 14:04:15', 'En el emocionante y complejo mundo de bienes raíces, contar con el asesoramiento de un experto es esencial para garantizar una experiencia exitosa y sin complicaciones. Los asesores inmobiliarios no solo aportan conocimiento y experiencia, sino que tambié'),
(49, 3, 'vistas/img/logo.png', 'Red de Contactos y Recursos', 'El Rol Crucial del Asesor Inmobiliario', 'Red-de-Contactos-y-Recursos', NULL, 'Los asesores inmobiliarios tienen una extensa red de contactos en la industria, que incluye a otros profesionales como abogados, agentes de préstamos hipotecarios y inspectores de propiedades. Esta red puede ser invaluable para agilizar el proceso de compra o venta y garantizar que todas las piezas del rompecabezas se ensamblen sin problemas.', 1, '2023-08-22 15:20:11', 'En el emocionante y complejo mundo de bienes raíces, contar con el asesoramiento de un experto es esencial para garantizar una experiencia exitosa y sin complicaciones. Los asesores inmobiliarios no solo aportan conocimiento y experiencia, sino que tambié'),
(50, 3, 'vistas/img/logo.png', 'Negociación Hábil', 'El Rol Crucial del Asesor Inmobiliario', 'Negociacion-Habil', NULL, 'La negociación es una parte integral de cualquier transacción inmobiliaria. Los asesores inmobiliarios tienen habilidades sólidas de negociación y pueden representarte en las discusiones con compradores, vendedores u otros agentes. Su objetivo es garantizar que obtengas el mejor trato posible, ya sea en términos de precio, condiciones o reparaciones.', 1, '2023-08-22 15:21:29', 'En el emocionante y complejo mundo de bienes raíces, contar con el asesoramiento de un experto es esencial para garantizar una experiencia exitosa y sin complicaciones. Los asesores inmobiliarios no solo aportan conocimiento y experiencia, sino que tambié'),
(51, 3, 'vistas/img/logo.png', 'Simplificación del Proceso', 'El Rol Crucial del Asesor Inmobiliario', 'Simplificacion-del-Proceso', NULL, 'El proceso de compra o venta de una propiedad puede ser abrumador debido a la cantidad de documentos, trámites y decisiones involucradas. Un asesor inmobiliario te ayudará a navegar por todos estos aspectos y a asegurarte de que cumplas con los requisitos legales y financieros.', 1, '2023-08-22 16:04:42', 'En el emocionante y complejo mundo de bienes raíces, contar con el asesoramiento de un experto es esencial para garantizar una experiencia exitosa y sin complicaciones. Los asesores inmobiliarios no solo aportan conocimiento y experiencia, sino que tambié');

-- 
-- Dumping data for table anuncios
--
-- Table sartech_gtninmuebles.anuncios does not contain any data (it is empty)

-- 
-- Dumping data for table administradores
--
-- Table sartech_gtninmuebles.administradores does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;